Update README.md
Hone12345678/worthIt pull request #44
Opened 2022-04-05 04:26 UTC by Hone12345678

2022-04-05 16:15 UTC, RossWestwater requested changes
This is really well written! I love the flow and how you are wording things. Just a few minor corrections:

- can we change "actually stand to gain" to "actually stands to gain"
- change "dirvers" to "drivers"
- change "or in some cases the driver make loose money." to "or in some cases the driver may lose money."

2022-04-05 23:37 UTC, dhalladay approved these changes

2022-04-05 23:38 UTC, lnguyen87 approved these changes
done

2022-04-06 00:48 UTC, RossWestwater approved these changes

2022-04-06 00:48 UTC, merged